### ISSUE TITLE
Overriding classes

### ISSUE THREAD

**Issue by satazor** [amadormf/react-breadcrumb#2]
You support `classes` so that we can override the default classes. Since I am using the BEM convention, I immediately tried to use this option. Still the original ones remain.. is this expected?

See attached screenshot:

<img width="695" alt="screen shot 2016-12-10 at 10 19 41 pm" src="https://cloud.githubusercontent.com/assets/1017236/21076571/cab4c8e4-bf26-11e6-90d9-ab343ffa2944.png">

**Comment by amadormf** [comment]
Yes, this is the use I wanted to give. I think this is better for reuse components.

**Comment by satazor** [comment]
I understand. Would you add a prop to signal that the classes should be overriden instead of appended? This is merely a stylistic issue as I don't like to see the non-BEM classes in the DOM, so I understand if you don't want to add such a feature.

**Comment by amadormf** [comment]
If you want you can open a PR with this modification. I do not see the problem of adding this change.
